### PR TITLE
Firebase dev merge to main branch pull request

### LINKED ISSUE #2: Bug: Document Id of user collection is not same with `auth.currentUser`UID
When we signup one account we will create a profile document in user collection. The document id is not same with `auth.currentUser` UID

### PR DESCRIPTION
**Pull request by xcosmosbox**
Write done DatabaseProtocol and FirebaseController code

### CODE REVIEW

**Comment by ChingYeeSelinaWong** [comment]
all good

**Review by ChingYeeSelinaWong — APPROVED** [review]

**Comment by Richardliu1228x** [comment]
cool

**Review by Richardliu1228x — APPROVED** [review]

**Comment by NiloySS** [comment]
looks good

**Comment by htsplex** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
dnktty, @zhangcy0203, @zlfsnowman, @bd17kaka, @TerrisZhao, @king19990102, @Dreamtel, @CraigLuo, @Wsgamer7, @Jarednuts, @YaphetsFannn, @ThomasLi10, @chefnpozi, @zhaodc, @haifengchui, @chengjingfeng, @lookstudio, @LinXueyuanStdio, @nodfe, @Vaceee, @coding-ming3, @zhangyuxiang12, @howellhux, @sunny377, @Dlory, @orekiqian, @pennkao, @taoguan, @yape, @ybbdnnl, @gG8Fkpxq, @davidkohcw, @feiyin01, @digjack, @Togatamiriooo, @alpha-xone, @jiaohu, @kylinholmes, @zhushuangquan001, @MaSandy, @dacianpeng, @lebronparker, @Ted8000, @MarquinhosL, @HAQ-13, @leeshen64, @usshopperone, @wxj783428795, @madkay, @fengyelingdu

**Comment by stephaneThannio** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lumanyu, @shiyanlou-addit, @93linf, @guyueyingmu, @joshinrai, @WaxgourdMax, @FXLP, @skywangda, @HadesRookie, @ernie55ernie, @tapawulige, @john123951, @richard1230, @yjymon, @XiaoyangzZ, @snowmois, @xq160717, @lihanyu-zero, @rx5194, @j0shF85, @fanchenghhh, @Mandule, @MariexAos, @rock-you, @728443778, @liyichao, @shede333, @JasonHong0807, @nullgit, @zxcvggrer, @ZFgan, @dahebolangkuan, @devin730, @ninjacn, @wdygh1997, @juideal, @MariBQ, @olorz, @ly95, @ziwon, @arduino2018, @dchentech, @javalover123, @XuHaoIgeneral, @jeckun, @xiaoxiaoxing88, @jiuzhou, @yaksheng, @likunNet, @Oscar1643

**Pull request merged**
